package types

// ChatManage represents the configuration and state for a chat session
// including query processing, search parameters, and model configurations
type ChatManage struct {
	SessionID    string     `json:"session_id"`              // Unique identifier for the chat session
	UserID       string     `json:"user_id"`                 // Unique identifier for the user
	Query        string     `json:"query,omitempty"`         // Original user query
	RewriteQuery string     `json:"rewrite_query,omitempty"` // Query after rewriting for better retrieval
	EnableMemory bool       `json:"enable_memory"`           // Whether memory feature is enabled
	History      []*History `json:"history,omitempty"`       // Chat history for context

	KnowledgeBaseIDs []string `json:"knowledge_base_ids"`      // IDs of knowledge bases to search (multi-KB support)
	KnowledgeIDs     []string `json:"knowledge_ids,omitempty"` // IDs of specific files to search (optional)
	// SearchTargets is the pre-computed unified search targets
	// Computed once at request entry point, used throughout the pipeline
	SearchTargets    SearchTargets `json:"-"`
	VectorThreshold  float64       `json:"vector_threshold"`  // Minimum score threshold for vector search results
	KeywordThreshold float64       `json:"keyword_threshold"` // Minimum score threshold for keyword search results
	EmbeddingTopK    int           `json:"embedding_top_k"`   // Number of top results to retrieve from embedding search
	VectorDatabase   string        `json:"vector_database"`   // Vector database type/name to use

	RerankModelID   string  `json:"rerank_model_id"`  // Model ID for reranking search results
	RerankTopK      int     `json:"rerank_top_k"`     // Number of top results after reranking
	RerankThreshold float64 `json:"rerank_threshold"` // Minimum score threshold for reranked results

	MaxRounds int `json:"max_rounds"` // Maximum history rounds used for rewrite/context

	ChatModelID      string           `json:"chat_model_id"`     // ID of the chat model to use
	SummaryConfig    SummaryConfig    `json:"summary_config"`    // Configuration for summary generation
	FallbackStrategy FallbackStrategy `json:"fallback_strategy"` // Strategy when no relevant results are found
	FallbackResponse string           `json:"fallback_response"` // Default response when fallback occurs
	FallbackPrompt   string           `json:"fallback_prompt"`   // Prompt for model-based fallback response

	EnableRewrite        bool   `json:"enable_rewrite"`         // Whether to enable rewrite
	EnableQueryExpansion bool   `json:"enable_query_expansion"` // Whether to enable query expansion with LLM
	RewritePromptSystem  string `json:"rewrite_prompt_system"`  // Custom system prompt for rewrite stage
	RewritePromptUser    string `json:"rewrite_prompt_user"`    // Custom user prompt for rewrite stage

	// Internal fields for pipeline data processing
	SearchResult    []*SearchResult   `json:"-"` // Results from search phase
	RerankResult    []*SearchResult   `json:"-"` // Results after reranking
	MergeResult     []*SearchResult   `json:"-"` // Final merged results after all processing
	Entity          []string          `json:"-"` // List of identified entities
	EntityKBIDs     []string          `json:"-"` // Knowledge base IDs with ExtractConfig enabled
	EntityKnowledge map[string]string `json:"-"` // KnowledgeID -> KnowledgeBaseID mapping for graph-enabled files
	GraphResult     *GraphData        `json:"-"` // Graph data from search phase
	UserContent     string            `json:"-"` // Processed user content
	ChatResponse    *ChatResponse     `json:"-"` // Final response from chat model

	// Event system for streaming responses
	EventBus  EventBusInterface `json:"-"` // EventBus for emitting streaming events
	MessageID string            `json:"-"` // Assistant message ID for event emission

	// Web search configuration (internal use)
	TenantID         uint64 `json:"-"` // Tenant ID for retrieving web search config
	WebSearchEnabled bool   `json:"-"` // Whether web search is enabled for this request

	// FAQ Strategy Settings
	FAQPriorityEnabled       bool    `json:"-"` // Whether FAQ priority strategy is enabled
	FAQDirectAnswerThreshold float64 `json:"-"` // Threshold for direct FAQ answer (similarity > this value)
	FAQScoreBoost            float64 `json:"-"` // Score multiplier for FAQ results

	// Image support for multimodal chat
	UserMessageID           string   `json:"-"` // User message ID for updating image captions after rewrite
	Images                  []string `json:"-"` // Image URLs for MultiContent in current user message
	ImageDescription        string   `json:"-"` // Image description (visual details + OCR text) generated by VLM (used as fallback for non-vision models)
	VLMModelID              string   `json:"-"` // Agent-configured VLM model ID for image analysis
	ChatModelSupportsVision bool     `json:"-"` // Whether the chat model accepts multimodal/image input
	SkipKBSearch            bool     `json:"-"` // Set by rewrite intent classification: true = skip KB retrieval
	Language                string   `json:"-"` // User language name for prompt placeholder (e.g. "Chinese (Simplified)", "English")
}

// Clone creates a deep copy of the ChatManage object
func (c *ChatManage) Clone() *ChatManage {
	// Deep copy knowledge base IDs slice
	knowledgeBaseIDs := make([]string, len(c.KnowledgeBaseIDs))
	copy(knowledgeBaseIDs, c.KnowledgeBaseIDs)

	// Deep copy knowledge IDs slice
	knowledgeIDs := make([]string, len(c.KnowledgeIDs))
	copy(knowledgeIDs, c.KnowledgeIDs)

	// Deep copy search targets slice
	searchTargets := make(SearchTargets, len(c.SearchTargets))
	for i, t := range c.SearchTargets {
		if t != nil {
			kidsCopy := make([]string, len(t.KnowledgeIDs))
			copy(kidsCopy, t.KnowledgeIDs)
			searchTargets[i] = &SearchTarget{
				Type:            t.Type,
				KnowledgeBaseID: t.KnowledgeBaseID,
				KnowledgeIDs:    kidsCopy,
			}
		}
	}

	return &ChatManage{
		Query:            c.Query,
		RewriteQuery:     c.RewriteQuery,
		SessionID:        c.SessionID,
		KnowledgeBaseIDs: knowledgeBaseIDs,
		KnowledgeIDs:     knowledgeIDs,
		SearchTargets:    searchTargets,
		VectorThreshold:  c.VectorThreshold,
		KeywordThreshold: c.KeywordThreshold,
		EmbeddingTopK:    c.EmbeddingTopK,
		MaxRounds:        c.MaxRounds,
		VectorDatabase:   c.VectorDatabase,
		RerankModelID:    c.RerankModelID,
		RerankTopK:       c.RerankTopK,
		RerankThreshold:  c.RerankThreshold,
		ChatModelID:      c.ChatModelID,
		SummaryConfig: SummaryConfig{
			MaxTokens:           c.SummaryConfig.MaxTokens,
			RepeatPenalty:       c.SummaryConfig.RepeatPenalty,
			TopK:                c.SummaryConfig.TopK,
			TopP:                c.SummaryConfig.TopP,
			FrequencyPenalty:    c.SummaryConfig.FrequencyPenalty,
			PresencePenalty:     c.SummaryConfig.PresencePenalty,
			Prompt:              c.SummaryConfig.Prompt,
			ContextTemplate:     c.SummaryConfig.ContextTemplate,
			NoMatchPrefix:       c.SummaryConfig.NoMatchPrefix,
			Temperature:         c.SummaryConfig.Temperature,
			Seed:                c.SummaryConfig.Seed,
			MaxCompletionTokens: c.SummaryConfig.MaxCompletionTokens,
			Thinking:            c.SummaryConfig.Thinking,
		},
		FallbackStrategy:     c.FallbackStrategy,
		FallbackResponse:     c.FallbackResponse,
		FallbackPrompt:       c.FallbackPrompt,
		RewritePromptSystem:  c.RewritePromptSystem,
		RewritePromptUser:    c.RewritePromptUser,
		EnableRewrite:        c.EnableRewrite,
		EnableQueryExpansion: c.EnableQueryExpansion,
		TenantID:             c.TenantID,
		// FAQ Strategy Settings
		FAQPriorityEnabled:       c.FAQPriorityEnabled,
		FAQDirectAnswerThreshold: c.FAQDirectAnswerThreshold,
		FAQScoreBoost:            c.FAQScoreBoost,
		UserMessageID:            c.UserMessageID,
		Images:                   append([]string(nil), c.Images...),
		ImageDescription:         c.ImageDescription,
		VLMModelID:               c.VLMModelID,
		ChatModelSupportsVision:  c.ChatModelSupportsVision,
		SkipKBSearch:             c.SkipKBSearch,
		Language:                 c.Language,
	}
}

// EventType represents different stages in the RAG (Retrieval Augmented Generation) pipeline
type EventType string

const (
	LOAD_HISTORY           EventType = "load_history"           // Load conversation history without rewriting
	REWRITE_QUERY          EventType = "rewrite_query"          // Query rewriting for better retrieval
	CHUNK_SEARCH           EventType = "chunk_search"           // Search for relevant chunks
	CHUNK_SEARCH_PARALLEL  EventType = "chunk_search_parallel"  // Parallel search: chunks + entities (legacy, kept for backward compat)
	ENTITY_SEARCH          EventType = "entity_search"          // Search for relevant entities
	CHUNK_RERANK           EventType = "chunk_rerank"           // Rerank search results
	CHUNK_MERGE            EventType = "chunk_merge"            // Merge similar chunks
	DATA_ANALYSIS          EventType = "data_analysis"          // Data analysis for CSV/Excel files
	INTO_CHAT_MESSAGE      EventType = "into_chat_message"      // Convert chunks into chat messages
	CHAT_COMPLETION        EventType = "chat_completion"        // Generate chat completion
	CHAT_COMPLETION_STREAM EventType = "chat_completion_stream" // Stream chat completion
	STREAM_FILTER          EventType = "stream_filter"          // Filter streaming output
	FILTER_TOP_K           EventType = "filter_top_k"           // Keep only top K results
	IMAGE_ANALYSIS         EventType = "image_analysis"         // Standalone VLM image analysis
	MEMORY_RETRIEVAL       EventType = "memory_retrieval"       // Retrieve memory context
	MEMORY_STORAGE         EventType = "memory_storage"         // Store conversation to memory
)

// PipelineStep represents a single step in a pipeline.
// A step with one event runs sequentially; a step with multiple events runs them in parallel.
type PipelineStep struct {
	Events []EventType
	Setup  func(original *ChatManage, clones []*ChatManage) // Optional: prepare clones before parallel execution
	Merge  func(original *ChatManage, clones []*ChatManage) // Optional: merge results after parallel execution
}

// Step creates a sequential single-event pipeline step.
func Step(e EventType) PipelineStep {
	return PipelineStep{Events: []EventType{e}}
}

// Parallel creates a parallel multi-event pipeline step.
// All events run concurrently, each on a clone of ChatManage.
func Parallel(events ...EventType) PipelineStep {
	return PipelineStep{Events: events}
}

// WithSetup attaches a setup function that prepares clones before parallel execution.
func (s PipelineStep) WithSetup(fn func(*ChatManage, []*ChatManage)) PipelineStep {
	s.Setup = fn
	return s
}

// WithMerge attaches a merge function that combines results after parallel execution.
func (s PipelineStep) WithMerge(fn func(*ChatManage, []*ChatManage)) PipelineStep {
	s.Merge = fn
	return s
}

// IsParallel returns true if this step runs multiple events concurrently.
func (s PipelineStep) IsParallel() bool {
	return len(s.Events) > 1
}

// String returns a human-readable representation for logging.
func (s PipelineStep) String() string {
	if len(s.Events) == 1 {
		return string(s.Events[0])
	}
	names := make([]string, len(s.Events))
	for i, e := range s.Events {
		names[i] = string(e)
	}
	return "parallel(" + joinStrings(names, ",") + ")"
}

func joinStrings(ss []string, sep string) string {
	result := ""
	for i, s := range ss {
		if i > 0 {
			result += sep
		}
		result += s
	}
	return result
}

// --- Built-in merge/setup functions for common parallel patterns ---

// SetupRewriteImageParallel prepares clones for parallel rewrite + image analysis.
// Clone 0 (REWRITE_QUERY): strips images so it uses the fast chat model for text-only rewrite.
// Clone 1 (IMAGE_ANALYSIS): keeps images for VLM analysis.
func SetupRewriteImageParallel(original *ChatManage, clones []*ChatManage) {
	if len(clones) >= 1 {
		clones[0].Images = nil // Force text-only path for rewrite clone
	}
}

// MergeRewriteImageResults merges results from parallel rewrite + image analysis.
// Rewrite clone provides: RewriteQuery, SkipKBSearch, History, Entity, EntityKBIDs, EntityKnowledge
// Image clone provides: ImageDescription
func MergeRewriteImageResults(dst *ChatManage, srcs []*ChatManage) {
	for _, src := range srcs {
		if src.RewriteQuery != "" && src.RewriteQuery != dst.Query {
			dst.RewriteQuery = src.RewriteQuery
		}
		if src.SkipKBSearch {
			dst.SkipKBSearch = true
		}
		if len(src.History) > 0 {
			dst.History = src.History
		}
		if len(src.Entity) > 0 {
			dst.Entity = src.Entity
		}
		if len(src.EntityKBIDs) > 0 {
			dst.EntityKBIDs = src.EntityKBIDs
		}
		if len(src.EntityKnowledge) > 0 {
			dst.EntityKnowledge = src.EntityKnowledge
		}
		if src.ImageDescription != "" {
			dst.ImageDescription = src.ImageDescription
		}
	}
}

// MergeSearchResults merges results from parallel chunk search + entity search.
// Concatenates SearchResult slices, merges GraphResult, and deduplicates by ID.
func MergeSearchResults(dst *ChatManage, srcs []*ChatManage) {
	for _, src := range srcs {
		dst.SearchResult = append(dst.SearchResult, src.SearchResult...)
		if src.GraphResult != nil {
			if dst.GraphResult == nil {
				dst.GraphResult = src.GraphResult
			} else {
				dst.GraphResult.Node = append(dst.GraphResult.Node, src.GraphResult.Node...)
				dst.GraphResult.Relation = append(dst.GraphResult.Relation, src.GraphResult.Relation...)
			}
		}
	}
	// Deduplicate SearchResult by ID
	seen := make(map[string]bool)
	unique := make([]*SearchResult, 0, len(dst.SearchResult))
	for _, r := range dst.SearchResult {
		if r != nil && !seen[r.ID] {
			seen[r.ID] = true
			unique = append(unique, r)
		}
	}
	dst.SearchResult = unique
}

// Pipline defines the sequence of pipeline steps for different chat modes.
// Steps with multiple events run in parallel; single-event steps run sequentially.
var Pipline = map[string][]PipelineStep{
	"chat": { // Simple chat without retrieval
		Step(CHAT_COMPLETION),
	},
	"chat_stream": { // Streaming chat without retrieval (no history)
		Step(CHAT_COMPLETION_STREAM),
		Step(STREAM_FILTER),
	},
	"chat_history_stream": { // Streaming chat with conversation history
		Step(LOAD_HISTORY),
		Step(MEMORY_RETRIEVAL),
		Step(CHAT_COMPLETION_STREAM),
		Step(STREAM_FILTER),
		Step(MEMORY_STORAGE),
	},
	"rag": { // Retrieval Augmented Generation
		Step(CHUNK_SEARCH),
		Step(CHUNK_RERANK),
		Step(CHUNK_MERGE),
		Step(INTO_CHAT_MESSAGE),
		Step(CHAT_COMPLETION),
	},
	"rag_stream": { // Streaming Retrieval Augmented Generation
		Parallel(REWRITE_QUERY, IMAGE_ANALYSIS).
			WithSetup(SetupRewriteImageParallel).
			WithMerge(MergeRewriteImageResults),
		Parallel(CHUNK_SEARCH, ENTITY_SEARCH).
			WithMerge(MergeSearchResults),
		Step(CHUNK_RERANK),
		Step(CHUNK_MERGE),
		Step(FILTER_TOP_K),
		Step(DATA_ANALYSIS),
		Step(INTO_CHAT_MESSAGE),
		Step(CHAT_COMPLETION_STREAM),
		Step(STREAM_FILTER),
	},
}
